### ISSUE TITLE
Package 'AnalyzeFMRI' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/MedicalImaging#5]
Package [AnalyzeFMRI](https://CRAN.R-project.org/package=AnalyzeFMRI) is currently listed in CRAN Task View [MedicalImaging](https://CRAN.R-project.org/view=MedicalImaging) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by ktabelow** [comment]
The maintainer of this package (Pierre Lafaye de Micheaux) plans to resolve the errors and re-introduce to CRAN asap.

**Comment by jonclayden** [comment]
Although Pierre has been in touch with me and with Karsten, the package isn't yet back on CRAN and we have reached the four-week deadline. I have therefore removed it from the task view for now, in commit 22389b9.
