### ISSUE TITLE
Package 'fslr' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/MedicalImaging#6]
Package [fslr](https://CRAN.R-project.org/package=fslr) is currently listed in CRAN Task View [MedicalImaging](https://CRAN.R-project.org/view=MedicalImaging) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by jonclayden** [comment]
I'm happy to take a look at this (plus issues #4 and #5), and contact the maintainers.

**Comment by bjw34032** [comment]
Thanks, Jon.  I'm surprised this particular package has been archived, but then I let one of my medical imaging packages slip off of CRAN too a year or so ago.

**Comment by jonclayden** [comment]
The root cause seems to be `neurobase` being archived, which seems even more surprising. I'll check in with John.

**Comment by ktabelow** [comment]
Already contacted John, but did not receive an answer, yet.

**Comment by jonclayden** [comment]
OK, thanks Karsten. I'll leave this issue, then, until we have an update from him on his plans.

**Comment by bjw34032** [comment]
I corresponded with John M yesterday and my `oro.nifti` package has caused `neurobase` to crash.  I have modified some code and v0.11.3 of `oro.nifti` has been accepted by CRAN (Uwe) this morning.

**Comment by jonclayden** [comment]
Package `fslr` is back on CRAN, so no further action is needed.
