### ISSUE TITLE
Package 'neuRosim' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/MedicalImaging#7]
Package [neuRosim](https://CRAN.R-project.org/package=neuRosim) is currently listed in CRAN Task View [MedicalImaging](https://CRAN.R-project.org/view=MedicalImaging) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by ktabelow** [comment]
I will contact Marijke Welvaert as maintainer of the package.

**Comment by ktabelow** [comment]
I contacted Marijke and will try to take over maintenance. Stay tuned.

**Comment by ktabelow** [comment]
Resubmitted to CRAN, pending confirmation

**Comment by jonclayden** [comment]
Great to hear - thanks Karsten!

**Comment by ktabelow** [comment]
Still struggling with re-submission. New NOTEs appeared from the dark ...

**Comment by ktabelow** [comment]
On CRAN again!
