### ISSUE TITLE
Package 'mritc' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/MedicalImaging#8]
Package [mritc](https://CRAN.R-project.org/package=mritc) is currently listed in CRAN Task View [MedicalImaging](https://CRAN.R-project.org/view=MedicalImaging) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by ktabelow** [comment]
Is anyone in contact with Dai Feng or Luke Tierney

**Comment by jonclayden** [comment]
Not currently, but I can drop Dei Feng a line as maintainer

**Comment by bjw34032** [comment]
Thanks, Jon.  I haven't been in contact with either of them for at least 10 years

**Comment by jonclayden** [comment]
I've been in touch with Dai, who isn't working in imaging any more, and so is more keen to transfer maintenance of the package to someone else than continue supporting it. I have what I believe are fixes for the outstanding issues and would be willing to take over as maintainer, unless anyone else is keen to do so instead.

**Comment by ktabelow** [comment]
Great! Go ahead ;)

**Comment by jonclayden** [comment]
This package is now back on CRAN, with me as the maintainer.
